### ISSUE TITLE
not installing?

### ISSUE THREAD

**Issue by bbrendon** [stabbylambda/quietcool-cli#1]
I'm hoping you can help me get this installed and working. I don't get a quietcool-cli program to run after installing it.  Are the warnings a problem? Am I doing something else wrong?
Thanks for any assistance!

```
# npm install -g quietcool-cli
/usr/lib
└── quietcool-cli@1.0.0

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.1.2 (node_modules/quietcool-cli/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
# node -v
v7.10.1
#

# pwd
/usr/lib/node_modules/quietcool-cli
# ls -la
total 120
drwxr-xr-x   3 nobody adm  4096 Apr  2 12:11 .
drwxr-xr-x   5 root   adm  4096 Apr  2 12:11 ..
-rw-r--r--   1 nobody adm  3870 Sep 14  2017 index.js
-rw-r--r--   1 nobody adm 11357 Sep 14  2017 LICENSE
drwxr-xr-x 284 root   adm 12288 Apr  2 12:11 node_modules
-rw-r--r--   1 nobody adm    18 Sep 14  2017 .npmignore
-rw-r--r--   1 nobody adm  2439 Apr  2 12:11 package.json
-rw-r--r--   1 nobody adm   399 Sep 14  2017 README.md
-rw-r--r--   1 nobody adm 73474 Sep 14  2017 yarn.lock

#

```

**Comment by stabbylambda** [comment]
I'll be perfectly honest: I've never installed it globally, so I never set up the bin directive in the package.json file.

I also think the cli project is probably out of date with the library because I've mostly been working on the web interface and homebridge integration. I'll take a look this evening when I get home (because the wifi controllers are there... 😛) and see if I can get the cli up to date and globally installable.

**Comment by bbrendon** [comment]
Okay thanks. I'm debating on whether to buy the wifi controller or not. If this works I'll buy it and make sure I can return it (just in case). Once I get it working I'll never upgrade the firmware. Heh.

**Comment by stabbylambda** [comment]
I just updated the cli project to use the latest API project. All you need to do is set your CONTROLLER_IP environment variable to the IP address of the controller and you can go poking around. If you're only using one controller, the iOS/Android app is pretty good and I'd probably use that over the CLI. But if you're using multiple, then the app tends to get a little buggy.

I'd also say it depends on what type of fan you have. I've got a Stealth that has two speeds, so finding a smart switch with multiple poles that interfaces with the fans is nearly impossible. But if your fan only has one speed, the controller is pretty useless because it's just a smart switch at that point.

**Comment by bbrendon** [comment]
Yea. I have a two speed as well.  I know I can use some relays and wifi switches to duplicate the controller but if I ever ditch Home Assistant or if its not working it'll be nice to have a supported controller. I plan to not use the phone app and to use quietcool-cli exclusively.
